version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/smscavenger
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  load-test:
    build:
      context: .
      target: builder
    command: npm run test:load:dev
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/smscavenger_test
    depends_on:
      - app
      - mongodb

volumes:
  mongodb_data: 